### PR TITLE
fix(containers): do not crash because of unhandled error

### LINKED ISSUE #323: Deploy fails with unhandled TypeError when container is in error state
### Community Note
- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### What did you do?

I triggered a deployment using the `serverless-scaleway-functions` plugin while one of my containers was in an `error` state (the container failed to start). The deployment was initiated via CI/CD (GitHub Actions).

### What did you expect to see?

Either a successful deployment that would override the errored container, or a clear, actionable error message explaining that the container is in an error state and cannot be redeployed in its current condition.

### What did you see instead?

The plugin crashed with an unhandled TypeError. It attempts to read the `status` property of an undefined value in `containers.js:118`, likely because the container object returned by the API is malformed or missing when the container is in an error state.

```
lifecycle:command:invoke:hook: [26] > deploy:deploy
process: handle error
process: finalize { error:
   { TypeError: Cannot read properties of undefined (reading 'status')
       at /home/runner/work/papavero/papavero/backend/node_modules/serverless-scaleway-functions/shared/api/containers.js:118:26
       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
       at async Promise.all (index 0)
Error:
     [stack]:
      "TypeError: Cannot read properties of undefined (reading 'status')\n    at /home/runner/work/papavero/papavero/backend/node_modules/serverless-scaleway-functions/shared/api/containers.js:118:26\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Promise.all (index 0)",
     [message]: "Cannot read properties of undefined (reading 'status')" },
  shouldBeSync: undefined,
  telemetryData: undefined,
  shouldSendTelemetry: undefined }
Environment: linux, node 20.20.0, framework 3.40.0, plugin 7.2.3, SDK 4.5.1

TypeError: Cannot read properties of undefined (reading 'status')
    at /home/runner/work/papavero/papavero/backend/node_modules/serverless-scaleway-functions/shared/api/containers.js:118:26
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
```

### What version of Node are you using (`node --version`)?

```sh
$ node --version
v20.x
```

### Does this issue reproduce with the latest release?

Yes

### PR DESCRIPTION
**Pull request by cyclimse**
## Summary

**_What's changed?_**

- Fix a bug where if the container is in error, we run a `throw Error`... but then in the catch statement, we try to access `error.response` which is obviously undefined for untyped errors like this. We should just forward it in this case
- Make function and container error handling consistent

Massive thanks to @lunhenry for the suggestion: https://github.com/scaleway/serverless-scaleway-functions/issues/323#issuecomment-4182892000 

**_Why do we need this?_**

- Currently, containers in error return an obscure error message instead of the helpful one set by the API

**_How have you tested it?_**

- N/A

## Checklist

- [x] I have reviewed this myself
- [ ] There is a unit test covering every change in this PR
- [ ] I have updated the relevant documentation

## Details

Closes #323 

For reviewers, I thought I broke it in: https://github.com/scaleway/serverless-scaleway-functions/pull/320/changes?diff=split#diff-a56d1acd44a4b5b77776b9f2d4d27ad62792c674d34f24a6d3b460ba96143b78 but actually it seems we had the issue previously

### CODE REVIEW

File: shared/api/containers.js [hunk 1]
```diff
@@ -113,13 +113,15 @@ module.exports = {
         return container;
       })
       .catch((err) => {
-        // There's no "deleted" status for container,
-        // so if the container is not found we consider it as deleted and return null
-        if (err.response.status === 404) {
-          return null;
+        // toleration on 4XX errors because on some status, for example deleting the API
```
Comment (cyclimse) [inline shared/api/containers.js:116]: For reviewers: this is a copy-paste of the error handling for FaaS: https://github.com/scaleway/serverless-scaleway-functions/blob/1ace7dbc61a9808c298214d7c5c0bf7a4215b35f/shared/api/functions.js#L117

**Review by Bemilie — APPROVED** [review]
