### PR TITLE
ensure registry image priority is serverless framework

### LINKED ISSUE #111: Container image not overwritten on later deployments
Steps to reproduce:
 - Deploy a container with the serverless framework
 - Change the image and tag manually in Scaleway Console
 - Redeploy with the serverless framework

I would have assumed the redeployment would overwrite the manually set image and tag, but it just seems to ignore the image/tag setting.

### PR DESCRIPTION
**Pull request by thomas-tacquet**
When assigning to a container an image from an other source (for example the console) it will not be updated on `serverless deploy` command

So I added in updating parameter the registry image to ensure it's the one pushed by serverless framework.

Closes #111

### CODE REVIEW

**Review by Shillaker — CHANGES_REQUESTED** [review]
Please tidy up the name of the PR and the description. 

Is this covered by an integration test? If not, can we add one?

File: deploy/lib/createContainers.js [hunk 1]
```diff
@@ -126,6 +127,6 @@ module.exports = {
     this.applyDomainsContainer(foundContainer.id, container.custom_domains);
 
     return this.updateContainer(foundContainer.id, params)
-      .then(response => Object.assign(response, { directory: container.directory }));
+      .then((response) => Object.assign(response, { directory: container.directory }));
```
Comment (norbjd) [inline deploy/lib/createContainers.js:130]: Unnecessary change I guess.

Comment (thomas-tacquet) [reply deploy/lib/createContainers.js:130]: linter, removed it 👌  ( `Arrow functions can omit parentheses when they have exactly one parameter. In all other cases the parameter(s) must be wrapped in parentheses. This rule enforces the consistent use of parentheses in arrow functions.` )

**Review by norbjd — APPROVED** [review]
